# Generated by Django 3.2.9 on 2021-11-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='name',
        ),
    ]
